name: "VPS Deploy"
on:
    push:
        branches:
            - master
jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: ssh key passphrase
              uses: appleboy/ssh-action@master
              with:
                  host: ${{ secrets.VPS_HOST }}
                  username: ${{ secrets.VPS_USERNAME }}
                  key: ${{ secrets.SSH_KEY }}
                  port: ${{ secrets.VPS_PORT }}
                  passphrase: ${{ secrets.SSH_PASSPHRASE }}
                  script: |
                      cd /var/www/dictionary-api
                      git pull origin master
                      yarn install
                      yarn build
                      pm2 restart index
